main: com.itsazza.noteblockeditor.NoteBlockEditorPlugin
name: NoteBlockEditor
version: 1.4.0
author: ItsAZZA
api-version: "1.13"
softdepend: ["NoteBlocksPlus"]
commands:
  noteblock:
    aliases: [noteblockeditor, nbe]
permissions:
  noteblockeditor.interact:
    description: "Access to the noteblock editor via interaction"
  noteblockeditor.command:
    description: "Access to the noteblock editor via command"
  noteblockeditor.reload:
    description: "Ability to reload configuration"
  noteblockeditor.bypass:
    description: "Bypass any build restrictions: able to edit noteblocks anywhere"
  noteblockeditor.give:
    description: "Ability to get and give pre-set noteblocks"
  noteblockeditor.place:
    description: "Ability to place noteblocks with pre-set values"
  noteblockeditor.instruments:
    default: true
    description: "Access to the noteblock editor instrument menu"